watch_stylesheet: true
watch_config: true
debug: false
update_check: true
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true 
      acrylic: false
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: true
      windows_app_bar: true 
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 45 #36
    padding:
      top: 6
      left: 10
      bottom: 6
      right: 10
    widgets:
      left: [
        "user",
        "clock",
        "media",
        # "komorebi_active_layout",
      ]
      center: [
        # "apps",
        # "taskbar",
        "komorebi_workspaces",
        "active_window",
      ]
      right: [
        # "systray", 
        # "wallpapers",
        # "weather",
        "cpu",
        "gpu",
        "brightness",
        "volume",
        "wifi",
        "battery",
        "power_menu",
      ]
widgets:
  user:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uedd2  {data}" #\ue683 \uedd2  
      label_alt: "User: {data}"
      callbacks:
        on_left: "exec cmd.exe /c explorer.exe %USERPROFILE%"
        on_right: "do_nothing"
      class_name: "user"
      exec_options:
        use_shell: true
        run_cmd: "echo %USERNAME%" 
        return_format: "string"
  sysinfo:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "sysinfo"
      widgets: [
        "cpu",
        "gpu"
      ]
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "cpu: {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      cpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
  gpu:
    type: "yasb.gpu.GpuWidget"
    options:
      label: "gpu: {info[utilization]}%"
      label_alt: "gpu: [{info[temp]} \udb81\udd04 | {info[mem_used]} / {info[mem_total]}]"
      update_interval: 2000
      gpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "toggle_label"
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\uf186 offline"
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: true
      hide_if_offline: false 
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "[ {win[process][name]} ]"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: false 
      label_icon_size: 14
      max_length: 30
      max_length_ellipsis: "..."
      monitor_exclusive: false
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b %I:%M %p}" # %H for 24-hour format %p for AM/PM %I for zero-padded hour
      label_alt: "{%A, %d %B %Y %H:%M:%S}"
      timezones: []
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "f5f6c59de5b84ee4bd7132309251601"
      show_alerts: true
      update_interval: 600
      hide_decimal: true
      units: "metric"
      location: "6201, Sibulan, Philippines"
      tooltip: true
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      icons: 
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzardDay: "\uebaa"
        default: "\uebaa"
      weather_card: 
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 64
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}% | time: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      status_icons:
        icon_charging: "\uf0e7"
        icon_critical: "\uf244"
        icon_low: "\uf243"
        icon_medium: "\uf242"
        icon_high: "\uf241"
        icon_full: "\uf240"
  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "{icon} {percent}%" 
      label_alt: "Brightness {percent}%"
      tooltip: true
      brightness_icons: [
        "\udb80\udcde",
        "\udb80\udcdd",
        "\udb80\udcdf",
        "\udb80\udce0"
      ]       
      callbacks:
        on_left: "toggle_label"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "{wifi_icon} {wifi_name}"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_menu"
        on_middle: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_label"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span>{ip_addr}"
      ethernet_icon: "\ueba9"
      get_exact_wifi_strength: false  # Optional. Will require location access permission if true.
      wifi_icons: [
        "\udb82\udd2f",  # Icon for 0% strength
        "\udb82\udd1f",  # Icon for 1-24% strength
        "\udb82\udd22",  # Icon for 25-49% strength
        "\udb82\udd25",  # Icon for 50-74% strength
        "\udb82\udd28"   # Icon for 75-100% strength
      ]
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        wifi_icons_secured: [
          "\udb82\udd21",
          "\udb82\udd24",
          "\udb82\udd27",
          "\udb82\udd2a",
        ]
        wifi_icons_unsecured: [
          "\udb82\udd20",
          "\udb82\udd23",
          "\udb82\udd26",
          "\udb82\udd29",
        ]
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\udb81\udc25" #\ue62a
      uptime: True
      blur: False
      blur_background: False
      animation_duration: 100
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\udb80\udf5e"
      label_expanded: "\udb80\udf5f"
      label_position: "right"
      icon_size: 16
      pin_click_modifier: "alt"
      show_unpinned: true
      show_battery: false
      show_volume: false
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist} - {title}"
      hide_empty: true
      callbacks:
        on_left: "toggle_play_pause"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      max_field_size:
        label: 30 
      show_thumbnail: true
      controls_only: false
      controls_left: false
      controls_hide: true 
      thumbnail_alpha: 50 
      thumbnail_padding: 0
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0a"
        pause: "\udb80\udfe4"
      scrolling_label:
        update_interval_ms: 20
        enabled: false 
        style: "bounce-ease"  # can be "left", "right", "bounce", "bounce-ease"
        # separator: "]  ["
        label_padding: 0
        # Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
        # ease_slope: 80
        # ease_pos: 0.34
        # ease_min: 0.16
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label: "{data}"
      app_list:
        - { icon: "\uf0a2", launch: "notification_center" }
        - { icon: "\uf002", launch: "search" }
        - { icon: "\uf437", launch: "cmd /c Taskmgr" }
        - { icon: "\uf489", launch: "wt", name: "Windows Terminal" }
        - { icon: "\ueb01", launch: "C:\\Program Files\\Zen Browser\\zen.exe", name: "Zen Browser" }
  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span>"
      label_alt: "Notifications {data}"
      token: env
      max_notification: 30
      only_unread: false
      max_field_size: 54
      menu_width: 400
      menu_height: 400
      menu_offset: 240
      update_interval: 60
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      hide_empty: true
      tooltip: true
      animation: false 
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\uf03e</span>"
      image_path: "C:\\Wallpapers"
      change_automatically: false 
      update_interval: 60 
      gallery:
        enabled: true 
        blur: true
        image_width: 220
        image_per_page: 8
        show_buttons: false
        orientation: "portrait"
        image_spacing: 8
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: false
